class backgrounds:
    backs = [
        'Abyssdweller',
        'Adept',
        'Adopted',
        'Adventurer',
        'Adventuring Royalty',
        'Afflicted',
        'Air Acrobat',
        'Alchemic Construct',
        'Alchemist',
        'Alcoholic',
        'Alcoholic Scientist',
        'Amnesiac',
        'Ancient Cultist',
        'Ancient One',
        'Antiquarian',
        'Apothecary',
        'Arcana Spy',
        'Arcane Augmented',
        'Arcane Dominion',
        'Archaeologist',
        'Armed Escort',
        'Arranged Marriage',
        'Artist',
        'Arvoreen Keeper',
        'Aspirant',
        'Astronaut',
        'Balloon Mage',
        'Banker',
        'Barmaid',
        'Battlesmith',
        'Beggar',
        'Bereaved',
        'Bodyguard',
        'Bounty Hunter',
        'Butler',
        'Cattle Rustler',
        'Changeling',
        'Child of Ares',
        'Chronicler',
        'City Guard',
        'City Worker',
        'Combat Medic',
        'Confederacy of Feuding Houses',
        'Conscript',
        'Construct',
        'Cook',
        'Courtesan',
        'Crazed Hermit',
        'Crusader Nation',
        'Cursed',
        'Dandy',
        'Dark Lord',
        'Demonologist',
        'Denizen',
        'Detective',
        'Diplomat',
        'Disciple of the Obscure',
        'Disgrace',
        'Disowned Noble',
        'Divine',
        'Doctor',
        'Dog of the Military',
        'Dragon Trained',
        'Drow Breeding Slave',
        'Drunken Bum',
        'Duelist',
        'Earthling',
        'Elysium Knight',
        'Employee of Royalty',
        'Endless Soul',
        'Engineer',
        'Envoy',
        'Eternal One',
        'Evil Cultist',
        'Ex Blood Doll',
        'Executioner',
        'Exile',
        'Exiled Ruler',
        'Experiment',
        'Explorer',
        'Falconer',
        'Fallen Hero',
        'Farmer',
        'Feared',
        'Fearful',
        'Feral Child',
        'Fey Child',
        'Firefighter',
        'Forgotten',
        'Gambler',
        'Gladiator',
        'God Touched',
        'Governess',
        'Gravetender',
        'Heir of a Fallen Kingdom',
        'Hellborn',
        'Herald of the Gods',
        'Heretic',
        'Hitman',
        'Hooded Figure',
        'House Worker',
        'Hunter',
        'Hunter Stalker',
        'Immortal',
        'Infected',
        'Innkeeper',
        'Inquirer',
        'Isekai',
        'Islander',
        'Janitor',
        'Jester',
        'Knight Sororitas',
        'Law Bringer',
        'Librarian',
        'Lone Survivor',
        'Lost Civilization',
        'Lover',
        'Lumberjack',
        'Mage Hunter',
        'Maid',
        'Mailman',
        'Marshal',
        'Master Inquisitor',
        'Member of The Court of Gaia',
        'Mercenary',
        'Messenger',
        'Metal Worker',
        'Militant assassin',
        'Military Asset',
        'Military Pilot',
        'Miner',
        'Monastic',
        'Monastic Traveller',
        'Monster',
        'Monster Hunter',
        'Mute',
        'Mystic',
        'Noble Dragon Tamer',
        'Noble Guard',
        'Nomad',
        'Oathbreaker',
        'Occult Investigator',
        'Of the Void',
        'Otherworlder',
        'Otherworlder',
        'Planar Traveler',
        'Plane Walker',
        'Politician',
        'Princess',
        'Prince',
        'Prisoner',
        'Professional Assassin',
        'Prospector',
        'Psychic',
        'Psycho',
        'Puppeteer',
        'Redeemed Cultist',
        'Regime of the Dark Overlord',
        'Revenant',
        'Revolutionist',
        'Rider',
        'Roamer',
        'Royal Cavalryman',
        'Royalty',
        'Runaway',
        'Salesman',
        'Savage Land',
        'Scavenger',
        'Scout',
        'Secret',
        'Seeker',
        'Sentinel',
        'Serial Killer',
        'Sex Worker',
        'Shadow Bringer',
        'Shadow Thieves' 'Guild Member',
        'Shipwright',
        'Simpleton',
        'Slayer',
        'Smuggler',
        'Smuggler',
        'Soulless',
        'Spirit Medium',
        'Split Personality',
        'Spy',
        'Squire',
        'Storyteller',
        'Student of Magic',
        'Survivor',
        'Tailor',
        'Temple Guardian',
        'Test Subject',
        'The Chosen One',
        'Transformed Monster',
        'Urban Vigilante',
        'Vagrant Trouper',
        'Vaquero',
        'Venator',
        'Wandering Mercenary',
        'War Criminal',
        'Warforged',
        'Well Travelled',
        'Witch Doctor',
        'Witch Hunter',
        'Woodcutter',
        'Wooddweller',
        'Worshipped One',
        'Writer',
        'Zealot'
    ]
